### PR TITLE
New Level 16!!

### PR DESCRIPTION
**Pull request by ktec**
This level should prove some kind of challenge.

### CODE REVIEW

**Comment by sharkdp** [comment]
I have uploaded the level here: https://shark.fish/curiosity/experimental/level016/chars.html

I haven't solved it, yet ... but I'll keep trying :smile:

**Comment by ktec** [comment]
Hi Peter, any luck? I'm looking forward to sharing this with a couple of friends

**Comment by pbraun** [comment]
(Not the Peter you're asking, but ...) I finished the level. It was fun, but I had to look up one of the URLs. Personally, I would never have guessed it. If I'm allowed to mention it here I'll let you know, which one.

**Comment by ktec** [comment]
Yeah I can bet its the last one yes? It kind of takes a "lateral" thinking leap  - I wasn't sure maybe we can add some hints to help with that one...

**Comment by pbraun** [comment]
It wasn't the last one. It was the one that had "+[]+=()". I could've used some kind of hint :-)

**Comment by ktec** [comment]
Yeah I suspected that one would be the sticking point. I've just added some new hints.

**Comment by sharkdp** [comment]
I tried not to read any of the conversation above...

I still haven't solved it .. do you have any tips for getting started? :smile:

**Comment by pbraun** [comment]
Hint: http://www.jsfuck.com/

**Comment by sharkdp** [comment]
Thanks for the hint! I was even thinking of Brainfuck, but I didn't realize this was valid JS... :hushed: 

With this hint, I managed to get to `boolean.html`, but I (also) have no idea what `[]+=()` is supposed to tell me.

**Comment by ktec** [comment]
Yeah we need a better hint for that, or change it - if you `count` the `number` of `______`

**Comment by sharkdp** [comment]
I still don't get it ... the `=` sign is not even part of jsfuck?

**Comment by ktec** [comment]
actually its not jsfuck, http://slides.com/sylvainpv/xchars-js/#/

**Comment by sharkdp** [comment]
I'm sorry, but I don't think this puzzle is a very good fit for curiositY. There are several reasons:

* most importantly, I think the required knowledge to solve this puzzle is far too specific. If I'm not mistaking, people have to know both jsfuck and the theoretical considerations how many characters are needed in order to represent arbitrary JavaScript code (and I couldn't find any proof that '6' is the lowest number anyway).. even then, I find it incredibly hard to guess `6chars` as the correct answer. And I believe it's not just me.. a few other people have also tried and failed.
* The puzzle has multiple stages... this is different from all other puzzles where only a single correct guess is required. The whole idea of curiositY is to have multiple stages, but they are typically not directly related to each other.
* curiositY already has a few JavaScript-related puzzles and I don't really want it to be all about JS. In addition, this level is rather similar to [Level 4](https://shark.fish/curiosity/level004/js.html), where JS code has to be executed / interpreted.

Thank you very much for this PR anyways. I am - in principle - very open to ideas for new puzzles.

**Pull request closed without merging**
